name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Format check (biome - informational only)
        run: npm run format:check || echo "⚠️ Biome format check failed - this is informational only"
        continue-on-error: true

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Upload coverage to Codecov
        if: matrix.node-version == 20
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  build-check:
    name: Build artifacts check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check build artifacts
        run: |
          echo "Checking that all expected build artifacts are present..."
          test -f dist/index.js || (echo "Missing dist/index.js" && exit 1)
          test -f dist/index.cjs || (echo "Missing dist/index.cjs" && exit 1)
          test -f dist/index.d.cts || (echo "Missing dist/index.d.cts" && exit 1)
          echo "All build artifacts present ✓"

      - name: Test exports
        run: |
          echo "Testing package exports..."
          node -e "const pkg = require('./dist/index.cjs'); console.log('CJS exports:', Object.keys(pkg).length, 'items');"
          node -e "import('./dist/index.js').then(pkg => console.log('ESM exports:', Object.keys(pkg).length, 'items'));"

  dependency-check:
    name: Dependency vulnerabilities
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: always